name: Update Vendor plugin - jekyll-anchor-headings
on:
  # schedule:
  #   # once per week
  #   - cron: "0 15 * * 0"
  workflow_dispatch:
jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get latest release information
        id: latest-release
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'allejo',
              repo: 'jekyll-anchor-headings'
            });
            core.setOutput('release', response.data.tag_name);

      - name: Download latest jekyll-anchor-headings file
        run: |
          LATEST_RELEASE=${{ steps.latest-release.outputs.release }}
          curl -L "https://github.com/allejo/jekyll-anchor-headings/releases/download/${LATEST_RELEASE}/anchor_headings.html" -o "_includes/vendor/anchor_headings.html"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore[dependency]: Update `jekyll-anchor-headings` to `${{ steps.latest-release.outputs.release }}`"
          title: "auto: Update `jekyll-anchor-headings` to `${{ steps.latest-release.outputs.release }}`"
          body: |
            Update `jekyll-anchor-headings` to `${{ steps.latest-release.outputs.release }}`
            This is an automated pull request.
          branch: update/vendor/jekyll-anchor-headings
          delete-branch: true
          labels: |
            kind/update
            area/dependency
          add-paths: |
            _includes/vendor/anchor_headings.html
